
import { config } from 'dotenv';
config();

import '@/ai/flows/adapt-content-grade-level.ts';
import '@/ai/flows/generate-answer-key-qr-code.ts';
import '@/ai/flows/photo-to-worksheet.ts';
import '@/ai/flows/generate-localized-content.ts';
import '@/ai/flows/generate-quiz.ts';
import '@/ai/flows/create-rubric.ts';
import '@/ai/flows/text-to-speech.ts';
import '@/ai/flows/enhance-writing.ts';
import '@/ai/flows/recognize-students.ts';
import '@/ai/flows/create-lesson-plan.ts';
import '@/ai/flows/generate-discussion.ts';
import '@/ai/flows/generate-visual-aid.ts';
import '@/ai/flows/ask-sahayak.ts';
import '@/ai/flows/get-tts-voices.ts';
import '@/ai/flows/create-presentation.ts';
import '@/ai/flows/teacher-pd.ts';
import '@/ai/flows/app-chatbot.ts';
import '@/ai/flows/create-worksheet.ts';
import '@/ai/flows/search-youtube-videos.ts';
import '@/ai/flows/create-mentorship-plan.ts';
import '@/ai/flows/generate-visual-aid.types.ts';
import '@/ai/flows/recognize-students.types.ts';
import '@/ai/flows/generate-localized-content.types.ts';
import '@/ai/flows/enhance-writing.types.ts';
import '@/ai/flows/create-presentation.types.ts';
import '@/ai/flows/create-lesson-plan.types.ts';
import '@/ai/flows/generate-discussion.types.ts';
import '@/ai/flows/ask-sahayak.types.ts';
import '@/ai/flows/get-tts-voices.types.ts';
import '@/ai/flows/teacher-pd.types.ts';
import '@/ai/flows/app-chatbot.types.ts';
import '@/ai/flows/create-worksheet.types.ts';
import '@/ai/flows/search-youtube-videos.types.ts';
import '@/ai/flows/create-mentorship-plan.types.ts';
